import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();

  const { isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>Twitter Emojis</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-300">
        {!isSignedIn && <SignInButton />}
        {isSignedIn && (
          <>
            <SignOutButton />
            <Composer />
          </>
        )}
        {data?.map((post) => (
          <div key={post.id} className="m-3 flex">
            <img width={40} alt="pic" src={post.author?.profileImageUrl} />
            <div>
              <div className="flex">
                {post.author?.username} . {dayjs(post.createdAt).fromNow()}
              </div>
              {post.content}
            </div>
          </div>
        ))}
      </main>
    </>
  );
};

function Composer() {
  const { user } = useUser();
  console.log(user);

  return (
    <div className="flex">
      <img width={40} alt="pic" src={user?.profileImageUrl} />
      <input />
    </div>
  );
}

export default Home;
